//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatteryNotifier.Setting {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class appSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static appSetting defaultInstance = ((appSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new appSetting())));
        
        public static appSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool fullBatteryNotification {
            get {
                return ((bool)(this["fullBatteryNotification"]));
            }
            set {
                this["fullBatteryNotification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool lowBatteryNotification {
            get {
                return ((bool)(this["lowBatteryNotification"]));
            }
            set {
                this["lowBatteryNotification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("96")]
        public int fullBatteryNotificationValue {
            get {
                return ((int)(this["fullBatteryNotificationValue"]));
            }
            set {
                this["fullBatteryNotificationValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int lowBatteryNotificationValue {
            get {
                return ((int)(this["lowBatteryNotificationValue"]));
            }
            set {
                this["lowBatteryNotificationValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fullBatteryNotificationMusic {
            get {
                return ((string)(this["fullBatteryNotificationMusic"]));
            }
            set {
                this["fullBatteryNotificationMusic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string lowBatteryNotificationMusic {
            get {
                return ((string)(this["lowBatteryNotificationMusic"]));
            }
            set {
                this["lowBatteryNotificationMusic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PinToNotificationArea {
            get {
                return ((bool)(this["PinToNotificationArea"]));
            }
            set {
                this["PinToNotificationArea"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool darkThemeApplied {
            get {
                return ((bool)(this["darkThemeApplied"]));
            }
            set {
                this["darkThemeApplied"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WindowPositionX {
            get {
                return ((int)(this["WindowPositionX"]));
            }
            set {
                this["WindowPositionX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WindowPositionY {
            get {
                return ((int)(this["WindowPositionY"]));
            }
            set {
                this["WindowPositionY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LaunchAtStartup {
            get {
                return ((bool)(this["LaunchAtStartup"]));
            }
            set {
                this["LaunchAtStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("68e189cd-278f-436f-b76a-8a4b75ec0b7c")]
        public string AppId {
            get {
                return ((string)(this["AppId"]));
            }
            set {
                this["AppId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SystemThemeApplied {
            get {
                return ((bool)(this["SystemThemeApplied"]));
            }
            set {
                this["SystemThemeApplied"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool startMinimized {
            get {
                return ((bool)(this["startMinimized"]));
            }
            set {
                this["startMinimized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int lowBatteryNotificationValue2 {
            get {
                return ((int)(this["lowBatteryNotificationValue2"]));
            }
            set {
                this["lowBatteryNotificationValue2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("70")]
        public int lowBatteryNotificationValue3 {
            get {
                return ((int)(this["lowBatteryNotificationValue3"]));
            }
            set {
                this["lowBatteryNotificationValue3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool lowBatteryNotification2 {
            get {
                return ((bool)(this["lowBatteryNotification2"]));
            }
            set {
                this["lowBatteryNotification2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool lowBatteryNotification3 {
            get {
                return ((bool)(this["lowBatteryNotification3"]));
            }
            set {
                this["lowBatteryNotification3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("🔋 Battery is low, please Connect to Charger.")]
        public string lowBatteryNotificationMessageTemplate {
            get {
                return ((string)(this["lowBatteryNotificationMessageTemplate"]));
            }
            set {
                this["lowBatteryNotificationMessageTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("🔋 Battery went over {0} threshold")]
        public string lowBatteryNotificationMessageTemplate2 {
            get {
                return ((string)(this["lowBatteryNotificationMessageTemplate2"]));
            }
            set {
                this["lowBatteryNotificationMessageTemplate2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("🔋Battery went over {0} threshold")]
        public string lowBatteryNotificationMessageTemplate3 {
            get {
                return ((string)(this["lowBatteryNotificationMessageTemplate3"]));
            }
            set {
                this["lowBatteryNotificationMessageTemplate3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:50")]
        public global::System.TimeSpan lowBatteryNotificationDuration {
            get {
                return ((global::System.TimeSpan)(this["lowBatteryNotificationDuration"]));
            }
            set {
                this["lowBatteryNotificationDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:50")]
        public global::System.TimeSpan lowBatteryNotificationDuration2 {
            get {
                return ((global::System.TimeSpan)(this["lowBatteryNotificationDuration2"]));
            }
            set {
                this["lowBatteryNotificationDuration2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:50")]
        public global::System.TimeSpan lowBatteryNotificationDuration3 {
            get {
                return ((global::System.TimeSpan)(this["lowBatteryNotificationDuration3"]));
            }
            set {
                this["lowBatteryNotificationDuration3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("🔋 Battery is full please unplug the charger.")]
        public string fullBatteryNotificationMessageTemplate {
            get {
                return ((string)(this["fullBatteryNotificationMessageTemplate"]));
            }
            set {
                this["fullBatteryNotificationMessageTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Full battery")]
        public string fullBatteryNotificationTitle {
            get {
                return ((string)(this["fullBatteryNotificationTitle"]));
            }
            set {
                this["fullBatteryNotificationTitle"] = value;
            }
        }
    }
}
